const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Flowchart,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Flowchart.Acts.StartFlowchart,
		C3.Plugins.Flowchart.Cnds.OnAnyNodeChange,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Flowchart.Exps.OutputValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Flowchart.Acts.GotoNextFlowchartNode,
		C3.Plugins.Flowchart.Acts.GotoPreviousFlowchartNode,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Flowchart.Acts.GotoAnyFlowchartNode,
		C3.Plugins.Flowchart.Cnds.OnTaggedNodeChange
	];
};
self.C3_JsPropNameTable = [
	{flc_AiG: 0},
	{txt_Frage: 0},
	{txt_Auswahl1: 0},
	{txt_Auswahl2: 0},
	{Mouse: 0},
	{txt_Zurück: 0},
	{spr_Background1: 0},
	{txt_Reset: 0},
	{spr_ButtonGrey: 0},
	{spr_InfoscreeGrey: 0},
	{txt_Hinweis1: 0},
	{txt_Hinweis2: 0},
	{txt_Hinweis3: 0},
	{Touch: 0},
	{txt_Titel: 0},
	{spr_Indicator: 0},
	{spr_ButtonGrey2: 0},
	{txt_Version: 0},
	{ButtonG: 0},
	{ButtonK: 0},
	{Field: 0},
	{Reset: 0},
	{Back: 0},
	{Header: 0},
	{spr_ButtonBlue: 0},
	{spr_MenuSymbol: 0},
	{spr_MenuHead: 0},
	{Position: 0},
	{MoveTo: 0},
	{spr_MenuRoll: 0},
	{AusweisR: 0},
	{spr_RahmenR: 0}
];

self.InstanceType = {
	flc_AiG: class extends self.IInstance {},
	txt_Frage: class extends self.ITextInstance {},
	txt_Auswahl1: class extends self.ITextInstance {},
	txt_Auswahl2: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	txt_Zurück: class extends self.ITextInstance {},
	spr_Background1: class extends self.ISpriteInstance {},
	txt_Reset: class extends self.ITextInstance {},
	spr_ButtonGrey: class extends self.ISpriteInstance {},
	spr_InfoscreeGrey: class extends self.ISpriteInstance {},
	txt_Hinweis1: class extends self.ITextInstance {},
	txt_Hinweis2: class extends self.ITextInstance {},
	txt_Hinweis3: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	txt_Titel: class extends self.ITextInstance {},
	spr_Indicator: class extends self.ISpriteInstance {},
	spr_ButtonGrey2: class extends self.ISpriteInstance {},
	txt_Version: class extends self.ITextInstance {},
	ButtonG: class extends self.ISpriteInstance {},
	ButtonK: class extends self.ISpriteInstance {},
	Field: class extends self.ISpriteInstance {},
	Reset: class extends self.ISpriteInstance {},
	Back: class extends self.ISpriteInstance {},
	Header: class extends self.ISpriteInstance {},
	spr_ButtonBlue: class extends self.ISpriteInstance {},
	spr_MenuSymbol: class extends self.ISpriteInstance {},
	spr_MenuHead: class extends self.ISpriteInstance {},
	spr_MenuRoll: class extends self.ISpriteInstance {},
	AusweisR: class extends self.ISpriteInstance {},
	spr_RahmenR: class extends self.ISpriteInstance {}
}