const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Flowchart,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Flowchart.Acts.StartFlowchart,
		C3.Plugins.Flowchart.Cnds.OnAnyNodeChange,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Flowchart.Exps.OutputValue,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Flowchart.Acts.GotoNextFlowchartNode,
		C3.Plugins.Flowchart.Acts.GotoPreviousFlowchartNode,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Flowchart.Acts.GotoAnyFlowchartNode,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Flowchart.Cnds.OnTaggedNodeChange
	];
};
self.C3_JsPropNameTable = [
	{flc_AiG: 0},
	{txt_Frage: 0},
	{txt_Auswahl1: 0},
	{txt_Auswahl2: 0},
	{Mouse: 0},
	{txt_Hinweis1: 0},
	{txt_Hinweis2: 0},
	{txt_Hinweis3: 0},
	{Touch: 0},
	{txt_Titel: 0},
	{txt_Version: 0},
	{spr_Reset: 0},
	{spr_Back: 0},
	{"9ptc_BackgroundWhite": 0},
	{"9ptc_BackgroundShadow": 0},
	{"9ptc_ButtonNEIN": 0},
	{"9ptc_ButtonJA": 0},
	{"9ptc_RoundWhite": 0},
	{"9ptc_RoundShadow": 0},
	{spr_Globe: 0},
	{spr_Thumb: 0},
	{spr_Siren: 0},
	{spr_BackInvisible: 0},
	{spr_RestInvisible: 0},
	{spr_InfoIconClose: 0},
	{"9ptc_InfoBackgroundWhite": 0},
	{"9ptc_InfoBackgroundShadow": 0},
	{txt_InfoNote: 0},
	{spr_InfoIconOpen: 0}
];

self.InstanceType = {
	flc_AiG: class extends self.IInstance {},
	txt_Frage: class extends self.ITextInstance {},
	txt_Auswahl1: class extends self.ITextInstance {},
	txt_Auswahl2: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	txt_Hinweis1: class extends self.ITextInstance {},
	txt_Hinweis2: class extends self.ITextInstance {},
	txt_Hinweis3: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	txt_Titel: class extends self.ITextInstance {},
	txt_Version: class extends self.ITextInstance {},
	spr_Reset: class extends self.ISpriteInstance {},
	spr_Back: class extends self.ISpriteInstance {},
	_9ptc_BackgroundWhite: class extends self.I9PatchInstance {},
	_9ptc_BackgroundShadow: class extends self.I9PatchInstance {},
	_9ptc_ButtonNEIN: class extends self.I9PatchInstance {},
	_9ptc_ButtonJA: class extends self.I9PatchInstance {},
	_9ptc_RoundWhite: class extends self.I9PatchInstance {},
	_9ptc_RoundShadow: class extends self.I9PatchInstance {},
	spr_Globe: class extends self.ISpriteInstance {},
	spr_Thumb: class extends self.ISpriteInstance {},
	spr_Siren: class extends self.ISpriteInstance {},
	spr_BackInvisible: class extends self.ISpriteInstance {},
	spr_RestInvisible: class extends self.ISpriteInstance {},
	spr_InfoIconClose: class extends self.ISpriteInstance {},
	_9ptc_InfoBackgroundWhite: class extends self.I9PatchInstance {},
	_9ptc_InfoBackgroundShadow: class extends self.I9PatchInstance {},
	txt_InfoNote: class extends self.ITextInstance {},
	spr_InfoIconOpen: class extends self.ISpriteInstance {}
}